-- Explicit, additive baseline for the Oracle PostgreSQL API.
-- Reviewed source contract plus application-owned booking/payment/job columns.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS "account_deletion_requests" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "account_deletion_requests" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "account_deletion_requests" ADD COLUMN IF NOT EXISTS "created_by" text;
ALTER TABLE "account_deletion_requests" ADD COLUMN IF NOT EXISTS "reason" text;
ALTER TABLE "account_deletion_requests" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "account_deletion_requests" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "account_deletion_requests" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "analytics_events" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "analytics_events" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "analytics_events" ADD COLUMN IF NOT EXISTS "dwell_ms" integer;
ALTER TABLE "analytics_events" ADD COLUMN IF NOT EXISTS "event_name" text;
ALTER TABLE "analytics_events" ADD COLUMN IF NOT EXISTS "event_type" text;
ALTER TABLE "analytics_events" ADD COLUMN IF NOT EXISTS "metadata" jsonb;
ALTER TABLE "analytics_events" ADD COLUMN IF NOT EXISTS "payload" jsonb;
ALTER TABLE "analytics_events" ADD COLUMN IF NOT EXISTS "post_id" text;
ALTER TABLE "analytics_events" ADD COLUMN IF NOT EXISTS "timestamp" text;
ALTER TABLE "analytics_events" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "analytics_events" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "availability" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "availability" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "availability" ADD COLUMN IF NOT EXISTS "day_of_week" integer;
ALTER TABLE "availability" ADD COLUMN IF NOT EXISTS "end_time" text;
ALTER TABLE "availability" ADD COLUMN IF NOT EXISTS "is_available" boolean;
ALTER TABLE "availability" ADD COLUMN IF NOT EXISTS "start_time" text;
ALTER TABLE "availability" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "availability" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "blocked_dates" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "blocked_dates" ADD COLUMN IF NOT EXISTS "blocked_date" text;
ALTER TABLE "blocked_dates" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "blocked_dates" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "blocked_dates" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "booking_events" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "booking_events" ADD COLUMN IF NOT EXISTS "actor_id" text;
ALTER TABLE "booking_events" ADD COLUMN IF NOT EXISTS "booking_id" text;
ALTER TABLE "booking_events" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "booking_events" ADD COLUMN IF NOT EXISTS "event_type" text;
ALTER TABLE "booking_events" ADD COLUMN IF NOT EXISTS "payload" jsonb;
ALTER TABLE "booking_events" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "bookings" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS start_datetime timestamptz;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS end_datetime timestamptz;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS package_id text;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS price_total numeric(14,2);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS is_instant boolean;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "accepted_at" timestamptz;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "addons" jsonb;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "assignment_state" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "booking_date" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "client_id" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "commission_amount" numeric(14,2);
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "completed_at" timestamptz;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "dispatch_request_id" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "distance_km" numeric(14,2);
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "eta_confidence" numeric(14,2);
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "fanout_count" integer;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "hold_expires_at" timestamptz;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "idempotency_key" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "intensity_level" integer;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "model_id" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "notes" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "package_type" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "payment_status" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "payout_amount" numeric(14,2);
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "photographer_id" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "photographer_payout" numeric(14,2);
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "pricing_mode" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "provider_latitude" double precision;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "provider_longitude" double precision;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "quote_amount" numeric(14,2);
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "quote_token" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "request_fingerprint" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "service_type" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "total_amount" numeric(14,2);
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "user_latitude" double precision;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "user_longitude" double precision;

CREATE TABLE IF NOT EXISTS "consent_events" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "consent_events" ADD COLUMN IF NOT EXISTS "consent_type" text;
ALTER TABLE "consent_events" ADD COLUMN IF NOT EXISTS "consent_version" text;
ALTER TABLE "consent_events" ADD COLUMN IF NOT EXISTS "context" jsonb;
ALTER TABLE "consent_events" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "consent_events" ADD COLUMN IF NOT EXISTS "enabled" boolean;
ALTER TABLE "consent_events" ADD COLUMN IF NOT EXISTS "legal_basis" text;
ALTER TABLE "consent_events" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "consent_events" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "contracts" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "body" text;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "booking_id" text;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "client_id" text;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "client_signature" text;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "contract_type" text;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "creator_id" text;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "creator_signature" text;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "model_id" text;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "model_signature" text;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "photographer_id" text;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "signed_by_client" boolean;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "signed_by_model" boolean;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "signed_by_photographer" boolean;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "title" text;
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "conversation_participants" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "conversation_participants" ADD COLUMN IF NOT EXISTS "conversation_id" text;
ALTER TABLE "conversation_participants" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "conversation_participants" ADD COLUMN IF NOT EXISTS "last_read_at" timestamptz;
ALTER TABLE "conversation_participants" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "conversation_participants" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "conversations" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "conversations" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "conversations" ADD COLUMN IF NOT EXISTS "created_by" text;
ALTER TABLE "conversations" ADD COLUMN IF NOT EXISTS "direct_key" text;
ALTER TABLE "conversations" ADD COLUMN IF NOT EXISTS "last_message" text;
ALTER TABLE "conversations" ADD COLUMN IF NOT EXISTS "last_message_at" timestamptz;
ALTER TABLE "conversations" ADD COLUMN IF NOT EXISTS "title" text;
ALTER TABLE "conversations" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "crash_logs" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "crash_logs" ADD COLUMN IF NOT EXISTS "context" jsonb;
ALTER TABLE "crash_logs" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "crash_logs" ADD COLUMN IF NOT EXISTS "error_message" text;
ALTER TABLE "crash_logs" ADD COLUMN IF NOT EXISTS "error_stack" text;
ALTER TABLE "crash_logs" ADD COLUMN IF NOT EXISTS "screen" text;
ALTER TABLE "crash_logs" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "crash_logs" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "credits_ledger" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "credits_ledger" ADD COLUMN IF NOT EXISTS "amount" numeric(14,2);
ALTER TABLE "credits_ledger" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "credits_ledger" ADD COLUMN IF NOT EXISTS "direction" text;
ALTER TABLE "credits_ledger" ADD COLUMN IF NOT EXISTS "reason" text;
ALTER TABLE "credits_ledger" ADD COLUMN IF NOT EXISTS "ref_id" text;
ALTER TABLE "credits_ledger" ADD COLUMN IF NOT EXISTS "ref_type" text;
ALTER TABLE "credits_ledger" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "credits_ledger" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "credits_wallets" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "credits_wallets" ADD COLUMN IF NOT EXISTS "balance" numeric(14,2);
ALTER TABLE "credits_wallets" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "credits_wallets" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "credits_wallets" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "dispatch_requests" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "dispatch_requests" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "dispatch_requests" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "dispatch_requests" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "earnings" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "earnings" ADD COLUMN IF NOT EXISTS "amount" numeric(14,2);
ALTER TABLE "earnings" ADD COLUMN IF NOT EXISTS "booking_id" text;
ALTER TABLE "earnings" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "earnings" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "earnings" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "earnings" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "eta_snapshots" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "eta_snapshots" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "eta_snapshots" ADD COLUMN IF NOT EXISTS "eta_confidence" numeric(14,2);
ALTER TABLE "eta_snapshots" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "follows" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "follows" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "follows" ADD COLUMN IF NOT EXISTS "follower_id" text;
ALTER TABLE "follows" ADD COLUMN IF NOT EXISTS "following_id" text;
ALTER TABLE "follows" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "job_outbox" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "job_outbox" ADD COLUMN IF NOT EXISTS "attempts" integer;
ALTER TABLE "job_outbox" ADD COLUMN IF NOT EXISTS "available_at" timestamptz;
ALTER TABLE "job_outbox" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "job_outbox" ADD COLUMN IF NOT EXISTS "dedupe_key" text;
ALTER TABLE "job_outbox" ADD COLUMN IF NOT EXISTS "kind" text;
ALTER TABLE "job_outbox" ADD COLUMN IF NOT EXISTS "last_error" text;
ALTER TABLE "job_outbox" ADD COLUMN IF NOT EXISTS "locked_at" timestamptz;
ALTER TABLE "job_outbox" ADD COLUMN IF NOT EXISTS "max_attempts" integer;
ALTER TABLE "job_outbox" ADD COLUMN IF NOT EXISTS "payload" jsonb;
ALTER TABLE "job_outbox" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "job_outbox" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "kyc_documents" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "kyc_documents" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "kyc_documents" ADD COLUMN IF NOT EXISTS "doc_type" text;
ALTER TABLE "kyc_documents" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "kyc_documents" ADD COLUMN IF NOT EXISTS "storage_path" text;
ALTER TABLE "kyc_documents" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "kyc_documents" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "location_tracks" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "location_tracks" ADD COLUMN IF NOT EXISTS "accuracy_m" numeric(14,2);
ALTER TABLE "location_tracks" ADD COLUMN IF NOT EXISTS "booking_id" text;
ALTER TABLE "location_tracks" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "location_tracks" ADD COLUMN IF NOT EXISTS "latitude" double precision;
ALTER TABLE "location_tracks" ADD COLUMN IF NOT EXISTS "longitude" double precision;
ALTER TABLE "location_tracks" ADD COLUMN IF NOT EXISTS "role" text;
ALTER TABLE "location_tracks" ADD COLUMN IF NOT EXISTS "source" text;
ALTER TABLE "location_tracks" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "location_tracks" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "media_access_logs" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "media_access_logs" ADD COLUMN IF NOT EXISTS "action" text;
ALTER TABLE "media_access_logs" ADD COLUMN IF NOT EXISTS "asset_id" text;
ALTER TABLE "media_access_logs" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "media_access_logs" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "media_access_logs" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "media_assets" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "media_assets" ADD COLUMN IF NOT EXISTS "booking_id" text;
ALTER TABLE "media_assets" ADD COLUMN IF NOT EXISTS "bucket" text;
ALTER TABLE "media_assets" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "media_assets" ADD COLUMN IF NOT EXISTS "is_locked" boolean;
ALTER TABLE "media_assets" ADD COLUMN IF NOT EXISTS "mime_type" text;
ALTER TABLE "media_assets" ADD COLUMN IF NOT EXISTS "object_path" text;
ALTER TABLE "media_assets" ADD COLUMN IF NOT EXISTS "owner_id" text;
ALTER TABLE "media_assets" ADD COLUMN IF NOT EXISTS "preview_url" text;
ALTER TABLE "media_assets" ADD COLUMN IF NOT EXISTS "price_zar" numeric(14,2);
ALTER TABLE "media_assets" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "media_assets" ADD COLUMN IF NOT EXISTS "thumbnail_url" text;
ALTER TABLE "media_assets" ADD COLUMN IF NOT EXISTS "title" text;
ALTER TABLE "media_assets" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "message_reactions" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "message_reactions" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "message_reactions" ADD COLUMN IF NOT EXISTS "emoji" text;
ALTER TABLE "message_reactions" ADD COLUMN IF NOT EXISTS "message_id" text;
ALTER TABLE "message_reactions" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "message_reactions" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "messages" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "audio_duration_seconds" text;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "audio_url" text;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "body" text;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "chat_id" text;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "deleted_at" timestamptz;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "locked" boolean;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "media_url" text;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "message_type" text;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "preview_url" text;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "read_at" timestamptz;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "reply_preview" jsonb;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "reply_to_id" text;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "sender_id" text;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "unlock_booking_id" text;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "unlock_price" numeric(14,2);
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "unlocked" boolean;
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "model_services" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "model_services" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "model_services" ADD COLUMN IF NOT EXISTS "is_active" boolean;
ALTER TABLE "model_services" ADD COLUMN IF NOT EXISTS "model_id" text;
ALTER TABLE "model_services" ADD COLUMN IF NOT EXISTS "rate_zar" numeric(14,2);
ALTER TABLE "model_services" ADD COLUMN IF NOT EXISTS "service_type" text;
ALTER TABLE "model_services" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "models" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "avatar_url" text;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "bio" text;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "categories" jsonb;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "equipment" jsonb;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "experience_years" text;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "gender" text;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "height" numeric(14,2);
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "hourly_rate" numeric(14,2);
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "is_available" boolean;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "is_online" boolean;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "latitude" double precision;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "location" text;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "longitude" double precision;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "name" text;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "portfolio_urls" jsonb;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "price_range" text;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "rating" numeric(14,2);
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "review_count" integer;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "specialties" jsonb;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "style" text;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "tags" jsonb;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "tier_id" text;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "total_bookings" integer;
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "travel_radius" numeric(14,2);
ALTER TABLE "models" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "moderation_cases" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "moderation_cases" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "moderation_cases" ADD COLUMN IF NOT EXISTS "reason" text;
ALTER TABLE "moderation_cases" ADD COLUMN IF NOT EXISTS "reporter_id" text;
ALTER TABLE "moderation_cases" ADD COLUMN IF NOT EXISTS "severity" text;
ALTER TABLE "moderation_cases" ADD COLUMN IF NOT EXISTS "sla_due_at" timestamptz;
ALTER TABLE "moderation_cases" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "moderation_cases" ADD COLUMN IF NOT EXISTS "target_id" text;
ALTER TABLE "moderation_cases" ADD COLUMN IF NOT EXISTS "target_type" text;
ALTER TABLE "moderation_cases" ADD COLUMN IF NOT EXISTS "target_user_id" text;
ALTER TABLE "moderation_cases" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "notification_events" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "notification_events" ADD COLUMN IF NOT EXISTS "action_payload" jsonb;
ALTER TABLE "notification_events" ADD COLUMN IF NOT EXISTS "action_type" text;
ALTER TABLE "notification_events" ADD COLUMN IF NOT EXISTS "body" text;
ALTER TABLE "notification_events" ADD COLUMN IF NOT EXISTS "category" text;
ALTER TABLE "notification_events" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "notification_events" ADD COLUMN IF NOT EXISTS "event_type" text;
ALTER TABLE "notification_events" ADD COLUMN IF NOT EXISTS "read_at" timestamptz;
ALTER TABLE "notification_events" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "notification_events" ADD COLUMN IF NOT EXISTS "title" text;
ALTER TABLE "notification_events" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "notification_events" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "payment_events" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "payment_events" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "payment_events" ADD COLUMN IF NOT EXISTS "event_type" text;
ALTER TABLE "payment_events" ADD COLUMN IF NOT EXISTS "payload" jsonb;
ALTER TABLE "payment_events" ADD COLUMN IF NOT EXISTS "payment_id" text;
ALTER TABLE "payment_events" ADD COLUMN IF NOT EXISTS "provider_event_id" text;
ALTER TABLE "payment_events" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "payment_incidents" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "payment_incidents" ADD COLUMN IF NOT EXISTS "amount" numeric(14,2);
ALTER TABLE "payment_incidents" ADD COLUMN IF NOT EXISTS "booking_id" text;
ALTER TABLE "payment_incidents" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "payment_incidents" ADD COLUMN IF NOT EXISTS "payment_id" text;
ALTER TABLE "payment_incidents" ADD COLUMN IF NOT EXISTS "reason" text;
ALTER TABLE "payment_incidents" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "payment_incidents" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "payments" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "amount" numeric(14,2);
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "booking_id" text;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "checkout_params" jsonb;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "currency" text;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "customer_id" text;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "idempotency_key" text;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "merchant_id" text;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "processed_at" timestamptz;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "provider" text;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "provider_payment_id" text;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "provider_status" text;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "settled_amount" numeric(14,2);
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "payout_methods" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "payout_methods" ADD COLUMN IF NOT EXISTS "account_holder" text;
ALTER TABLE "payout_methods" ADD COLUMN IF NOT EXISTS "account_masked" text;
ALTER TABLE "payout_methods" ADD COLUMN IF NOT EXISTS "account_type" text;
ALTER TABLE "payout_methods" ADD COLUMN IF NOT EXISTS "bank_name" text;
ALTER TABLE "payout_methods" ADD COLUMN IF NOT EXISTS "branch_code" text;
ALTER TABLE "payout_methods" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "payout_methods" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "payout_methods" ADD COLUMN IF NOT EXISTS "user_id" text;
ALTER TABLE "payout_methods" ADD COLUMN IF NOT EXISTS "verified" boolean;

CREATE TABLE IF NOT EXISTS "payout_requests" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "payout_requests" ADD COLUMN IF NOT EXISTS "amount" numeric(14,2);
ALTER TABLE "payout_requests" ADD COLUMN IF NOT EXISTS "booking_id" text;
ALTER TABLE "payout_requests" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "payout_requests" ADD COLUMN IF NOT EXISTS "payout_method_id" text;
ALTER TABLE "payout_requests" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "payout_requests" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "payout_requests" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "photographer_equipment" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "photographer_equipment" ADD COLUMN IF NOT EXISTS "camera_body" text;
ALTER TABLE "photographer_equipment" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "photographer_equipment" ADD COLUMN IF NOT EXISTS "extras" text;
ALTER TABLE "photographer_equipment" ADD COLUMN IF NOT EXISTS "lenses" text;
ALTER TABLE "photographer_equipment" ADD COLUMN IF NOT EXISTS "lighting" text;
ALTER TABLE "photographer_equipment" ADD COLUMN IF NOT EXISTS "photographer_id" text;
ALTER TABLE "photographer_equipment" ADD COLUMN IF NOT EXISTS "tier_id" text;
ALTER TABLE "photographer_equipment" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "photographers" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "avatar_url" text;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "bio" text;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "equipment" jsonb;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "experience_years" text;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "hourly_rate" numeric(14,2);
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "is_available" boolean;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "is_online" boolean;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "latitude" double precision;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "location" text;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "longitude" double precision;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "name" text;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "portfolio_urls" jsonb;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "price_range" text;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "rating" numeric(14,2);
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "review_count" integer;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "specialties" jsonb;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "style" text;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "tags" jsonb;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "tier_id" text;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "total_bookings" integer;
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "travel_radius" numeric(14,2);
ALTER TABLE "photographers" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "policy_violations" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "policy_violations" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "policy_violations" ADD COLUMN IF NOT EXISTS "entity_id" text;
ALTER TABLE "policy_violations" ADD COLUMN IF NOT EXISTS "entity_type" text;
ALTER TABLE "policy_violations" ADD COLUMN IF NOT EXISTS "policy_code" text;
ALTER TABLE "policy_violations" ADD COLUMN IF NOT EXISTS "severity" text;
ALTER TABLE "policy_violations" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "policy_violations" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "policy_violations" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "post_bookmarks" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "post_bookmarks" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "post_bookmarks" ADD COLUMN IF NOT EXISTS "post_id" text;
ALTER TABLE "post_bookmarks" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "post_bookmarks" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "post_comments" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "post_comments" ADD COLUMN IF NOT EXISTS "author_id" text;
ALTER TABLE "post_comments" ADD COLUMN IF NOT EXISTS "body" text;
ALTER TABLE "post_comments" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "post_comments" ADD COLUMN IF NOT EXISTS "post_id" text;
ALTER TABLE "post_comments" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "post_comments" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "post_likes" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "post_likes" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "post_likes" ADD COLUMN IF NOT EXISTS "post_id" text;
ALTER TABLE "post_likes" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "post_likes" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "post_unlocks" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "post_unlocks" ADD COLUMN IF NOT EXISTS "amount_paid" numeric(14,2);
ALTER TABLE "post_unlocks" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "post_unlocks" ADD COLUMN IF NOT EXISTS "post_id" text;
ALTER TABLE "post_unlocks" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "post_unlocks" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "posts" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "posts" ADD COLUMN IF NOT EXISTS "author_id" text;
ALTER TABLE "posts" ADD COLUMN IF NOT EXISTS "caption" text;
ALTER TABLE "posts" ADD COLUMN IF NOT EXISTS "comment_count" integer;
ALTER TABLE "posts" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "posts" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE "posts" ADD COLUMN IF NOT EXISTS "is_locked" boolean;
ALTER TABLE "posts" ADD COLUMN IF NOT EXISTS "likes_count" integer;
ALTER TABLE "posts" ADD COLUMN IF NOT EXISTS "location" text;
ALTER TABLE "posts" ADD COLUMN IF NOT EXISTS "media_type" text;
ALTER TABLE "posts" ADD COLUMN IF NOT EXISTS "media_url" text;
ALTER TABLE "posts" ADD COLUMN IF NOT EXISTS "moderation_status" text;
ALTER TABLE "posts" ADD COLUMN IF NOT EXISTS "price_zar" numeric(14,2);
ALTER TABLE "posts" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "posts" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "profiles" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bio text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS contact_details jsonb;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS verified boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS age_verified boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS age_verified_at timestamptz;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS date_of_birth text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_test_account boolean DEFAULT false;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "availability_status" text;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "avatar_url" text;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "city" text;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "full_name" text;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "gender" text;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "instagram" text;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "is_model" boolean;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "is_photographer" boolean;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "kyc_status" text;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "location_enabled" boolean;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "marketing_opt_in" boolean;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "personalized_ads" boolean;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "push_token" text;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "username" text;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "website" text;

CREATE TABLE IF NOT EXISTS "push_tokens" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "enabled" boolean;
ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "expo_push_token" text;
ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "last_seen_at" timestamptz;
ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "platform" text;
ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "reports" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "created_by" text;
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "details" text;
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "reason" text;
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "reporter_id" text;
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "target_id" text;
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "target_type" text;
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "reviews" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "reviews" ADD COLUMN IF NOT EXISTS "booking_id" text;
ALTER TABLE "reviews" ADD COLUMN IF NOT EXISTS "client_id" text;
ALTER TABLE "reviews" ADD COLUMN IF NOT EXISTS "comment" text;
ALTER TABLE "reviews" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "reviews" ADD COLUMN IF NOT EXISTS "moderation_status" text;
ALTER TABLE "reviews" ADD COLUMN IF NOT EXISTS "photographer_id" text;
ALTER TABLE "reviews" ADD COLUMN IF NOT EXISTS "rating" numeric(14,2);
ALTER TABLE "reviews" ADD COLUMN IF NOT EXISTS "reviewee_id" text;
ALTER TABLE "reviews" ADD COLUMN IF NOT EXISTS "reviewer_id" text;
ALTER TABLE "reviews" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "reviews" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "status_scores" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "status_scores" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "status_scores" ADD COLUMN IF NOT EXISTS "scene_rank" numeric(14,2);
ALTER TABLE "status_scores" ADD COLUMN IF NOT EXISTS "seen_score" numeric(14,2);
ALTER TABLE "status_scores" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "status_scores" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "stories" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "stories" ADD COLUMN IF NOT EXISTS "author_id" text;
ALTER TABLE "stories" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "stories" ADD COLUMN IF NOT EXISTS "duration" numeric(14,2);
ALTER TABLE "stories" ADD COLUMN IF NOT EXISTS "expires_at" timestamptz;
ALTER TABLE "stories" ADD COLUMN IF NOT EXISTS "media_type" text;
ALTER TABLE "stories" ADD COLUMN IF NOT EXISTS "media_url" text;
ALTER TABLE "stories" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "stories" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "subscription_tiers" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "subscription_tiers" ADD COLUMN IF NOT EXISTS "color" text;
ALTER TABLE "subscription_tiers" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "subscription_tiers" ADD COLUMN IF NOT EXISTS "creator_id" text;
ALTER TABLE "subscription_tiers" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "subscription_tiers" ADD COLUMN IF NOT EXISTS "is_active" boolean;
ALTER TABLE "subscription_tiers" ADD COLUMN IF NOT EXISTS "max_subscribers" integer;
ALTER TABLE "subscription_tiers" ADD COLUMN IF NOT EXISTS "name" text;
ALTER TABLE "subscription_tiers" ADD COLUMN IF NOT EXISTS "perks" jsonb;
ALTER TABLE "subscription_tiers" ADD COLUMN IF NOT EXISTS "price" numeric(14,2);
ALTER TABLE "subscription_tiers" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "subscriptions" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "creator_id" text;
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "current_period_end" timestamptz;
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "current_period_start" timestamptz;
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "subscriber_id" text;
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "tier_id" text;
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "support_tickets" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "support_tickets" ADD COLUMN IF NOT EXISTS "category" text;
ALTER TABLE "support_tickets" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "support_tickets" ADD COLUMN IF NOT EXISTS "created_by" text;
ALTER TABLE "support_tickets" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "support_tickets" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "support_tickets" ADD COLUMN IF NOT EXISTS "subject" text;
ALTER TABLE "support_tickets" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "support_tickets" ADD COLUMN IF NOT EXISTS "user_id" text;

CREATE TABLE IF NOT EXISTS "tip_goals" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "tip_goals" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "tip_goals" ADD COLUMN IF NOT EXISTS "creator_id" text;
ALTER TABLE "tip_goals" ADD COLUMN IF NOT EXISTS "is_active" boolean;
ALTER TABLE "tip_goals" ADD COLUMN IF NOT EXISTS "target_amount" numeric(14,2);
ALTER TABLE "tip_goals" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "tips" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "tips" ADD COLUMN IF NOT EXISTS "amount" numeric(14,2);
ALTER TABLE "tips" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "tips" ADD COLUMN IF NOT EXISTS "message" text;
ALTER TABLE "tips" ADD COLUMN IF NOT EXISTS "receiver_id" text;
ALTER TABLE "tips" ADD COLUMN IF NOT EXISTS "sender_id" text;
ALTER TABLE "tips" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "tips" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "user_blocks" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "user_blocks" ADD COLUMN IF NOT EXISTS "blocked_id" text;
ALTER TABLE "user_blocks" ADD COLUMN IF NOT EXISTS "blocker_id" text;
ALTER TABLE "user_blocks" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "user_blocks" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS "user_consents" (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE "user_consents" ADD COLUMN IF NOT EXISTS "accepted" boolean;
ALTER TABLE "user_consents" ADD COLUMN IF NOT EXISTS "accepted_at" timestamptz;
ALTER TABLE "user_consents" ADD COLUMN IF NOT EXISTS "consent_type" text;
ALTER TABLE "user_consents" ADD COLUMN IF NOT EXISTS "created_at" timestamptz DEFAULT now();
ALTER TABLE "user_consents" ADD COLUMN IF NOT EXISTS "enabled" boolean;
ALTER TABLE "user_consents" ADD COLUMN IF NOT EXISTS "granted" boolean;
ALTER TABLE "user_consents" ADD COLUMN IF NOT EXISTS "granted_at" timestamptz;
ALTER TABLE "user_consents" ADD COLUMN IF NOT EXISTS "legal_basis" text;
ALTER TABLE "user_consents" ADD COLUMN IF NOT EXISTS "metadata" jsonb;
ALTER TABLE "user_consents" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz DEFAULT now();
ALTER TABLE "user_consents" ADD COLUMN IF NOT EXISTS "user_id" text;
ALTER TABLE "user_consents" ADD COLUMN IF NOT EXISTS "version" text;

CREATE UNIQUE INDEX IF NOT EXISTS bookings_client_idempotency_idx ON bookings (client_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS availability_user_day_idx ON availability (user_id, day_of_week);
CREATE UNIQUE INDEX IF NOT EXISTS blocked_dates_user_date_idx ON blocked_dates (user_id, blocked_date);
CREATE UNIQUE INDEX IF NOT EXISTS push_tokens_user_token_idx ON push_tokens (user_id, expo_push_token);
CREATE UNIQUE INDEX IF NOT EXISTS model_services_user_type_idx ON model_services (model_id, service_type);
CREATE UNIQUE INDEX IF NOT EXISTS kyc_user_type_idx ON kyc_documents (user_id, doc_type);
CREATE UNIQUE INDEX IF NOT EXISTS follows_pair_idx ON follows (follower_id, following_id);
CREATE UNIQUE INDEX IF NOT EXISTS post_likes_pair_idx ON post_likes (post_id, user_id);
CREATE UNIQUE INDEX IF NOT EXISTS post_bookmarks_pair_idx ON post_bookmarks (post_id, user_id);
CREATE UNIQUE INDEX IF NOT EXISTS conversations_direct_key_idx ON conversations (direct_key) WHERE direct_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS conversation_membership_idx ON conversation_participants (conversation_id, user_id);
CREATE UNIQUE INDEX IF NOT EXISTS reviews_booking_author_idx ON reviews (booking_id, client_id) WHERE booking_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS payments_booking_active_idx ON payments (booking_id) WHERE status IN ('pending', 'completed');
CREATE UNIQUE INDEX IF NOT EXISTS earnings_booking_idx ON earnings (booking_id);
CREATE UNIQUE INDEX IF NOT EXISTS job_outbox_dedupe_idx ON job_outbox (dedupe_key);
CREATE UNIQUE INDEX IF NOT EXISTS payment_events_provider_idx ON payment_events (provider_event_id);
CREATE UNIQUE INDEX IF NOT EXISTS payout_requests_booking_idx ON payout_requests (booking_id);
CREATE INDEX IF NOT EXISTS bookings_provider_time_idx ON bookings (photographer_id, model_id, start_datetime, end_datetime);
CREATE INDEX IF NOT EXISTS job_outbox_ready_idx ON job_outbox (status, available_at);
ALTER TABLE tip_goals ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS client_signed_at timestamptz;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS model_signed_at timestamptz;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS photographer_signed_at timestamptz;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS signed_at timestamptz;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE consent_events ADD COLUMN IF NOT EXISTS captured_at timestamptz;
ALTER TABLE crash_logs ADD COLUMN IF NOT EXISTS app_version text;
ALTER TABLE crash_logs ADD COLUMN IF NOT EXISTS platform text;
